### ISSUE TITLE
Modules 2A-2F need data from old modules migrated

### ISSUE THREAD

**Issue by tmcelrath** [EntCollNet/BugFlow#15]
Draft Module Name | iDigBio Module Name
-- | --
2A - Initiating a Digitization Project | Module 0: Generic Tasks Applicable to Two or More Modules
2B - Quality Control | Module 5: Quality Assurance of Data
2C - In house data cleanup | split from Module 5
2D - Community data cleanup | split from Module 5
2E - Disseminating Data: Serving data to aggregators | N/A
2F - Workflow Metadata | N/A

**Comment by ekrimmel** [comment]
I migrated Module 2A, including comments.

**Comment by tmcelrath** [comment]
@mandrewj Migrated some text to 2C from Module 5.

**Comment by tmcelrath** [comment]
@debpaul migrated a bunch to 2B - just need 2D left to close this issue.

**Comment by tmcelrath** [comment]
All data from Module 5 has been migrated. Closing issue.
