### ISSUE TITLE
We need a collaborators/people/contact us page

### ISSUE THREAD

**Issue by tmcelrath** [EntCollNet/BugFlow#49]
Related to #48 - we need a splash page for the people involved and who should be listed as contacts.

**Comment by dryopoiddarling** [comment]
Yeah, want to use my slide with the people as an image? We could maybe add
institutions too. It was just a lot of info for the powerpoint.

On Tue, Nov 10, 2020 at 12:37 PM Tommy McElrath <notifications@github.com>
wrote:

> Related to #48
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EntCollNet_BugFlow_issues_48&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=tvuZmDAQ5Z5duBMS7wU_taIR4oboD9uVFgyoPLnt5xc&m=OjlsnmF7AQVmPbOg_BCDH2np8S1GC7LY_FYAFjVNv-I&s=csFpsgOEaN4YkL58wqkbXk7aKZyHZ1Ik2hxw2P_9t8g&e=>
> - we need a splash page for the people involved and who should be listed as
> contacts.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_EntCollNet_BugFlow_issues_49&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=tvuZmDAQ5Z5duBMS7wU_taIR4oboD9uVFgyoPLnt5xc&m=OjlsnmF7AQVmPbOg_BCDH2np8S1GC7LY_FYAFjVNv-I&s=HzDiKrk46BYvfKNyL-Ymp4pCdAxXwRDLTzTj2QwJstk&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQIWRGWFCPVEBMQMAW3DRXTSPF26VANCNFSM4TQ6UFKA&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=tvuZmDAQ5Z5duBMS7wU_taIR4oboD9uVFgyoPLnt5xc&m=OjlsnmF7AQVmPbOg_BCDH2np8S1GC7LY_FYAFjVNv-I&s=QfNeym14LENb_8_lAVdur3LITgBnH-Oi_S5CtXHs4B0&e=>
> .
>


-- 
Crystal A. Maier, Ph.D.
Curatorial Associate, Entomology
Museum of Comparative Zoology, Harvard University
26 Oxford Street, Cambridge, MA, 02138 U.S.A.

cmaier@fas.harvard.edu
+1-617-496-1055

**Comment by mandrewj** [comment]
@dryopoiddarling - we can link to your recorded video once it is posted as a start!  Or put the slides within the repo here, or link to slideshare or something too.

I added a little more to the home readme about joining us as well (as did someone else, @tmcelrath maybe?)

**Comment by tmcelrath** [comment]
@mandrewj are you talking about https://github.com/EntCollNet/BugFlow/blob/master/README.md - I haven't touched it, you can see that in the History :)

**Comment by mandrewj** [comment]
I was lazy.  It was Deb.

Closing this issue, as I have created the start of a user page:
https://github.com/EntCollNet/BugFlow/blob/master/about_us.md

Will comment in slack to ask folks to put their info in as they are comfortable. I didn't want to put it up without folks approval first!
