### ISSUE TITLE
Module 1D: Proactive Data Capture: In Museum [1st Draft Completion List]

### ISSUE THREAD

**Issue by tmcelrath** [EntCollNet/BugFlow#55]
[Module Link](https://github.com/EntCollNet/BugFlow/blob/master/modules/module_1/module_1D.md)
- [x] Title created
- [x] Purpose created
- [x] Keywords created
- [x] Point Person assigned
- [x] Task List filled in
- [x] Essential training added
- [x] Metrics costing reporting filled in
- [x] Outreach opportunities filled in
- [x] Exemplar workflows added
- [x] References to other Modules added/linked
- [x] Discussion section added at bottom
- [x] Links to standards/Best practices

**Comment by tmcelrath** [comment]
Priorities: etc ... may be covered: https://docs.google.com/document/d/1nakVdskiYTjLzWHrnS74-4ylTSyGTbnlhUuML1l5hgo/edit

**Comment by dryopoiddarling** [comment]
Migrated comment from 5A: Capturing field notes as a workflow process may need to be developed?
https://docs.google.com/document/d/1nakVdskiYTjLzWHrnS74-4ylTSyGTbnlhUuML1l5hgo/edit

**Comment by dryopoiddarling** [comment]
Migrated comment from 5A: We need to add references to the idea of adding metacollections/paracollections:
e.g. https://spnhc.biowikifarm.net/wiki/Field_Notes

**Comment by tmcelrath** [comment]
Closed with cd8b1fa
