### ISSUE TITLE
2F - Workflow metadata and plan

### ISSUE THREAD

**Issue by dryopoiddarling** [EntCollNet/BugFlow#82]
When I am a newcomer to BugFlow
Then I want to create a new workflow
So we need a new template for adding workflows to BugFlow.
These workflows need to have the proper metadata. 

Essential information and plan for adding institutional workflows to GitHub

**Comment by dryopoiddarling** [comment]
Each workflow added to the repository requires certain metadata for submission:

- Title (what is this workflow?)
- Authorship
- Copyright/License information
- Institution
- Date Created
- Date last modified
- keywords
- Database being used 
- Link to a pdf file

**Comment by dryopoiddarling** [comment]
2 options for submission: 
- Create new workflow using markdown
-  Upload pdf file, with license information

**Comment by tmcelrath** [comment]
Created new Issue Template here: https://github.com/EntCollNet/BugFlow/blob/master/.github/ISSUE_TEMPLATE/Add-Your-Workflow.md Closing with 7339fea
